accounts/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import UserProfileView, EditProfile

app_name ="accounts"

urlpatterns = [
    path('<username>', UserProfileView.as_view(), name="profile"),
    path('profile/edit', EditProfile, name="edit-profile")
]

core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include
from .views import HomeView, UserProductListView, ProductUpdateView, ProductDetailView

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('users/', include('accounts.urls', namespace='users')),

    path('', HomeView.as_view(), name='home'),
    path('products/', UserProductListView.as_view(), name='product-list'),
    path('products/<slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/<slug>/update/', ProductUpdateView.as_view(), name='product-update'),
    path("__reload__/", include("django_browser_reload.urls")),

    path('smarket/', include('smarket.urls', namespace='smarket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL)

templates/components/footer.html
{% load static %}
{% url 'home' as home %}
{% url 'product-list' as productlist %}

<footer class="py-6 w-full text-white bg-blue-500">
	<div class="container px-6 mx-auto space-y-6 divide-y divide-coolGray-400 md:space-y-12 divide-opacity-50">
		<div class="grid grid-cols-12">
			<div class="pb-6 col-span-full md:pb-0 md:col-span-6">
				<div class="flex justify-center space-x-3 md:justify-start">
					<div class="flex items-center justify-center w-40 h-40">
						<img class="flex-shrink-0 w-40" src="{% static 'logo_white.png' %}" alt="Smarket">
					</div>
				</div>
			</div>
			{% if user.is_authenticated %}
			<div class="col-span-6 text-center md:text-left md:col-span-3 mt-8">
				<p class="pb-1 text-lg font-medium">Usuario</p>
				<ul>
					<li>
						<a href="{% url 'users:profile' user.username %}" class="hover:dark:text-gray-400">Perfíl</a>
					</li>
					<li>
						<a href="{% url 'product-list' %}" class="hover:dark:text-gray-400">Mis Productos</a>
					</li>
				</ul>
			</div>
			{% else %}
			<div class="col-span-6 text-center md:text-left md:col-span-3 mt-8">
				<p class="pb-1 text-lg font-medium">Cuenta</p>
				<ul>
					<li>
						<a href="{% url 'account_login' %}" class="hover:dark:text-gray-400">Inicia Sesión</a>
					</li>
					<li>
						<a href="{% url 'account_signup' %}" class="hover:dark:text-gray-400">Registrate</a>
					</li>
				</ul>
			</div>
			{% endif %}
			<div class="col-span-6 text-center md:text-left md:col-span-3 mt-8">
				<p class="pb-1 text-lg font-medium">Sobre Nosotros</p>
				<ul>
					<li>
						<a href="#" class="hover:dark:text-gray-400">Acerca de</a>
					</li>
					<li>
						<a href="#" class="hover:dark:text-gray-400">Preguntas Frecuentes</a>
					</li>
					<li>
				</ul>
			</div>
		</div>
		<div class="grid justify-center pt-6 lg:justify-between">
			<div class="flex flex-col self-center text-sm text-center md:block lg:col-start-1 md:space-x-6">
				<span>©2022 Todos los derechos reservados</span>
				<a href="#">
					<span>Terminos de Servicio</span>
				</a>
				<a href="#">
					<span>Desarrollado por Federico Pintos</span>
				</a>
			</div>
			<div class="flex justify-center pt-4 space-x-4 lg:pt-0 lg:col-end-13">
				<a href="mailto:federicopintos.dev@gmail.com" title="Email"
					class="flex items-center justify-center w-10 h-10 rounded-full">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);">
						<path d="M18.73,5.41l-1.28,1L12,10.46,6.55,6.37l-1.28-1A2,2,0,0,0,2,7.05V18.64A1.36,1.36,0,0,0,3.36,20H6.55V12.28L12,16.37l5.45-4.09V20h3.19A1.36,1.36,0,0,0,22,18.64V7.05A2,2,0,0,0,18.73,5.41Z"></path>
					</svg>
				</a>
				<a href="https://www.linkedin.com/in/federico-pintos/" title="Linkedin" target="_blank"
					class="flex items-center justify-center w-10 h-10 rounded-full">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);"><circle cx="4.983" cy="5.009" r="2.188"></circle>
						<path d="M9.237 8.855v12.139h3.769v-6.003c0-1.584.298-3.118 2.262-3.118 1.937 0 1.961 1.811 1.961 3.218v5.904H21v-6.657c0-3.27-.704-5.783-4.526-5.783-1.835 0-3.065 1.007-3.568 1.96h-.051v-1.66H9.237zm-6.142 0H6.87v12.139H3.095z"></path>
					</svg>
				</a>
				<a href="https://github.com/fedeuhr" title="GitHub" target="_blank"
					class="flex items-center justify-center w-10 h-10 rounded-full">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);">
						<path fill-rule="evenodd" clip-rule="evenodd" d="M12.026 2c-5.509 0-9.974 4.465-9.974 9.974 0 4.406 2.857 8.145 6.821 9.465.499.09.679-.217.679-.481 0-.237-.008-.865-.011-1.696-2.775.602-3.361-1.338-3.361-1.338-.452-1.152-1.107-1.459-1.107-1.459-.905-.619.069-.605.069-.605 1.002.07 1.527 1.028 1.527 1.028.89 1.524 2.336 1.084 2.902.829.091-.645.351-1.085.635-1.334-2.214-.251-4.542-1.107-4.542-4.93 0-1.087.389-1.979 1.024-2.675-.101-.253-.446-1.268.099-2.64 0 0 .837-.269 2.742 1.021a9.582 9.582 0 0 1 2.496-.336 9.554 9.554 0 0 1 2.496.336c1.906-1.291 2.742-1.021 2.742-1.021.545 1.372.203 2.387.099 2.64.64.696 1.024 1.587 1.024 2.675 0 3.833-2.33 4.675-4.552 4.922.355.308.675.916.675 1.846 0 1.334-.012 2.41-.012 2.737 0 .267.178.577.687.479C19.146 20.115 22 16.379 22 11.974 22 6.465 17.535 2 12.026 2z"></path>
					</svg>
				</a>
			</div>
		</div>
	</div>
</footer>

templates/components/navbar.html
{% load static %}
{% url 'home' as home %}
{% url 'product-list' as productlist %}

<div x-data="{open:false}" class="relative bg-white shadow">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center py-4 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <a href="{% url 'home' %}">
          <span class="sr-only">Smarket</span>
          <img class="h-8 w-auto sm:h-10" src="{% static 'logo.png' %}" alt="Smarket">
        </a>
      </div>
      <div class="-mr-2 -my-2 md:hidden">
        <button @click="open=true" type="button"
          class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500"
          aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M15 13l-3 3m0 0l-3-3m3 3V8m0 13a9 9 0 110-18 9 9 0 010 18z" />
          </svg>
        </button>
      </div>
      <nav class="hidden md:flex space-x-10">
        <a href="{% url 'home' %}"
          class="{% if request.path == home %} text-base font-medium text-gray-900 {% else %}  text-base font-medium text-gray-500 hover:text-gray-900 {% endif %}">
          Smarket
        </a>
        {% if user.is_authenticated %}
        <a href="{% url 'product-list' %}"
          class="{% if request.path == productlist %} text-base font-medium text-gray-900 {% else %} text-base font-medium text-gray-500 hover:text-gray-900 {% endif %}">
          Mis Productos
        </a>
        {% endif %}
      </nav>
      <div x-data="{open:false}" class="z-10 flex items-center md:ml-12">
        {% if user.is_authenticated %}
        <div class="relative inline-block text-left">
          <div>
            <button @click="open=true" type="button"
              class="inline-flex justify-center w-full rounded-md px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500"
              id="menu-button" aria-expanded="true" aria-haspopup="true">
              <img class="inline-block rounded-lg w-8 h-8" src="{{user.profile.picture.url}}" alt="">
            </button>
          </div>
          <div x-show="open" @click.away="open=false"
            class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
            role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1" role="none">
              <a href="{% url 'users:profile' user.username %}" class="text-gray-500 block px-5 py-2 text-sm"
                role="menuitem" tabindex="-1" id="menu-item-0">Perfíl</a>
              <a href="{% url 'product-list' %}" class="text-gray-500 block px-5 py-2 text-sm" role="menuitem"
                tabindex="-1" id="menu-item-0">Mis Productos</a>
              <a href="{% url 'account_logout' %}" class="text-gray-500 block w-full text-left px-4 py-2 text-sm"
                role="menuitem" tabindex="-1" id="menu-item-3">
                Cerrar Sesión
              </a>
            </div>
          </div>
        </div>
        {% else %}
        <a href="{% url 'account_login' %}"
          class="whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900">
          Inicia Sesión
        </a>
        <a href="{% url 'account_signup' %}"
          class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-blue-500 hover:bg-blue-600">
          Registrate
        </a>
        {% endif %}
      </div>
    </div>
  </div>
  <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0"
    x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200"
    x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"
    class="z-10 absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
    <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
      <div class="pt-5 pb-6 px-5">
        <div class="flex items-center justify-between">
          <div>
            <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="Smarket">
          </div>
          <div class="-mr-2">
            <button @click="open=false" type="button"
              class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500">
              <span class="sr-only">Close menu</span>
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="mt-6">
          <nav class="grid gap-y-8">
            <a href="{% url 'home' %}" class="-m-3 p-3 flex items-center rounded-md hover:bg-gray-50">
              <span class="ml-3 text-base font-medium text-gray-900">
                Smarket
              </span>
            </a>
            <a href="{% url 'product-list' %}" class="-m-3 p-3 flex items-center rounded-md hover:bg-gray-50">
              <span class="ml-3 text-base font-medium text-gray-900">
                Mis Productos
              </span>
            </a>
          </nav>
        </div>
      </div>
      <div class="py-6 px-5 space-y-6">
        {% if user.is_authenticated %}
        <a href="{% url 'users:profile' user.username %}" class="flex-shrink-0 group block">
          <div class="flex-items-center">
            <div>
              <img class="inline-block h-9 w-9 rounded-full" src="{{user.profile.picture.url}}" alt="">
            </div>
            <div class="ml-3">
              <p class="text-sm font-medium text-gray-700 group-hover:text-gray-900">
                {{user.username}}
              </p>
              <p class="text-xs font-medium text-gray-500 text-hover:text-gray-700">
                Ver perfil
              </p>
            </div>
          </div>
        </a>
        {% else %}
        <div class="mt-6">
          <a href="{% url 'account_signup' %}"
            class="w-full flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-blue-500 hover:bg-blue-600">
            Registrarse
          </a>
          <p class="mt-6 text-center text-base font-medium text-gray-500">
            Ya tienes usuario?
            <a href="{% url 'account_login' %}" class="text-blue-500 hover:text-blue-600">
              Iniciar Sesión
            </a>
          </p>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>